version: '3'

services:
  nginx:
    image: nginx:1.13.5-alpine
    container_name: nginx
    networks:
      - one
      - two
    volumes:
      - ./nginx.config:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/ssl/
    ports:
      - "80:80"
      - "443:443"
    command: nginx -g 'daemon off;'

  alpha:
    image: nginx:1.13.5-alpine
    container_name: alpha
    volumes:
      - ./alpha.html:/usr/share/nginx/html/index.html
    networks:
      - one

  beta:
    image: nginx:1.13.5-alpine
    container_name: beta
    volumes:
      - ./beta.html:/usr/share/nginx/html/index.html
    networks:
      - two

  gamma:
    image: nginx:1.13.5-alpine
    container_name: gamma
    volumes:
      - ./gamma.html:/usr/share/nginx/html/index.html
    networks:
      - one
      - two


networks:
  one:
    driver: bridge
  two:
    driver: bridge